# Generated by Django 4.0.5 on 2022-06-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='flia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('identificacion', models.IntegerField()),
                ('nacionalidad', models.CharField(max_length=20)),
                ('fecha_naci', models.DateField()),
            ],
        ),
    ]
